baseURL = "/"
languageCode = "en-us"
title = "Urban Outdoorsy"
disableKinds = []

theme = "ananke"

[outputs]
home = ["HTML", "RSS"]
posts = ["HTML", "RSS"]

[params]
  showReadingTime = true
  showToc = true
  disableBreadcrumb = true

  [params.homeInfoParams]
    enable = true

[menu]

  [[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

  [[menu.main]]
  name = "About"
  url = "/about/"
  weight = 2

  [[menu.main]]
  name = "Posts"
  url = "/posts/"
  weight = 3

