name: UrbanOutdoorsy CI/CD 
run-name: ${{ github.actor }} pushed changes 🚀
on: 
  push:
    branches:
      - master
      - hugo
      - 'releases/**'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1 - Checks-out your repository
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."

      # Step 2 - Sets up Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.119.0'  # Use the latest version or specify a version
          extended: true

      # Step 3 - Build the Hugo site
      - name: Build site
        run: hugo --minify

      # step 4 setup sshpass
      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      # Step 5 - setup hosts
      - name: Setup knownhosts
        run: |
          mkdir -p ~/.ssh/ && touch ~/.ssh/known_hosts
          ssh-keyscan ${{ secrets.HOSTING_IP }} >> ~/.ssh/known_hosts
          eval $(ssh-agent)
      - run: echo "starting deployment to host"

      # Step 6 - Deploy to the server
      - name: deploy to host
        run: |
          cd public
          sshpass -p '${{ secrets.HOSTING_PWD }}' rsync --exclude '*.md' --exclude '.git' --exclude '.github' -r ./ ${{ secrets.HOSTING_USER }}@${{ secrets.HOSTING_IP }}:${{ secrets.HOSTING_PATH }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
